#!/usr/bin/env bash
# Quick Reference - All commands in one place
# Copy this file to use as a quick reference
# Usage: ./QUICK_REFERENCE.sh or just read it

echo "🏥 Hospital Management System - Quick Reference"
echo ""
echo "📋 Documentation Files:"
echo "  README.md                  - Main documentation and quickstart"
echo "  PRODUCTION_GUIDE.md        - Complete deployment guide"
echo "  CONTRIBUTING.md            - How to contribute"
echo "  SETUP_SUMMARY.md           - What's new in this version"
echo "  PRE_DEPLOYMENT_CHECKLIST.md- Deployment verification"
echo ""
echo "🚀 Quick Start Commands:"
echo ""
echo "  1. FIRST TIME SETUP:"
echo "     ./scripts/setup.sh"
echo ""
echo "  2. LOCAL DEVELOPMENT (Traditional):"
echo "     Backend:  cd backend && python manage.py runserver 0.0.0.0:8000"
echo "     Frontend: cd frontend && npm run dev"
echo ""
echo "  3. LOCAL DEVELOPMENT (Docker):"
echo "     ./scripts/docker-up.sh"
echo ""
echo "  4. DATABASE MIGRATIONS:"
echo "     ./scripts/migrate.sh"
echo ""
echo "  5. RUN TESTS:"
echo "     cd backend && python manage.py test"
echo ""
echo "  6. BUILD DOCKER IMAGE:"
echo "     docker build -t hospital-management:latest ."
echo ""
echo "  7. DEPLOY TO RENDER:"
echo "     git push origin main  # Auto-deploys"
echo ""
echo "📁 Project Directories:"
echo "  backend/       - Django API"
echo "  frontend/      - React + Vite"
echo "  scripts/       - Utility scripts"
echo "  .github/       - GitHub Actions CI/CD"
echo ""
echo "🔗 Service URLs (Local):"
echo "  Frontend:      http://localhost:5173"
echo "  Backend API:   http://localhost:8000/api"
echo "  Admin Panel:   http://localhost:8000/admin"
echo "  Database:      localhost:5432"
echo "  Health Check:  http://localhost:8000/api/health/"
echo ""
echo "🔐 Environment Setup:"
echo "  1. Copy environment template:"
echo "     cp .env.example .env"
echo "  2. Edit .env with your values"
echo "  3. Never commit .env file!"
echo ""
echo "🐳 Docker Commands:"
echo "  docker-compose up -d                   - Start services"
echo "  docker-compose down                    - Stop services"
echo "  docker-compose logs -f                 - View logs"
echo "  docker-compose exec backend sh         - Shell into backend"
echo "  docker-compose build --no-cache        - Rebuild images"
echo ""
echo "🗄️  Database Commands:"
echo "  python manage.py migrate               - Apply migrations"
echo "  python manage.py makemigrations        - Create migrations"
echo "  python manage.py createsuperuser       - Create admin user"
echo "  python manage.py shell                 - Django shell"
echo ""
echo "✅ Verification Commands:"
echo "  curl http://localhost:8000/api/health/"
echo "  python manage.py check --deploy        # Before production"
echo "  cd frontend && npm run build           # Frontend build"
echo ""
echo "📊 Important Environment Variables:"
echo "  SECRET_KEY              - Django secret key (generate: openssl rand -hex 32)"
echo "  DEBUG                   - False in production"
echo "  DATABASE_URL            - PostgreSQL connection string"
echo "  ALLOWED_HOSTS           - Comma-separated list of domains"
echo "  CORS_ALLOWED_ORIGINS    - Frontend domain for API access"
echo "  VITE_API_URL            - Backend API URL for frontend"
echo ""
echo "📚 Useful Links:"
echo "  Django Docs:       https://docs.djangoproject.com"
echo "  DRF Docs:          https://www.django-rest-framework.org"
echo "  React Docs:        https://react.dev"
echo "  Docker Docs:       https://docs.docker.com"
echo "  Render Docs:       https://render.com/docs"
echo "  Vercel Docs:       https://vercel.com/docs"
echo ""
echo "🆘 Troubleshooting:"
echo "  See PRODUCTION_GUIDE.md for common issues"
echo "  See README.md for quick troubleshooting"
echo "  Check health endpoint: curl http://localhost:8000/api/health/"
echo ""
echo "🎯 Before Deploying to Production:"
echo "  1. Run PRE_DEPLOYMENT_CHECKLIST.md"
echo "  2. Backup database: pg_dump \$DATABASE_URL > backup.sql"
echo "  3. Test locally with Docker: ./scripts/docker-up.sh"
echo "  4. Review PRODUCTION_GUIDE.md"
echo "  5. Set environment variables in Render dashboard"
echo "  6. Push to main branch: git push origin main"
echo ""
echo "✨ Need Help?"
echo "  📖 Read README.md for comprehensive guide"
echo "  🔍 Check PRODUCTION_GUIDE.md for deployment issues"
echo "  🤝 See CONTRIBUTING.md for contribution guidelines"
echo "  ✅ Use PRE_DEPLOYMENT_CHECKLIST.md before deploying"
echo ""
