services:
  - type: web
    name: hospital-management
    plan: free
    env: python
    buildCommand: |
      cd backend &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      cd ../frontend &&
      npm install &&
      npm run build &&
      cp -rf dist/* ../backend/static/
    startCommand: cd backend && gunicorn hospital_system.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
    autoDeploy: true
