import { Router } from "express";
import { db, prescriptionsTable, billingTable, usersTable, medicalRecordsTable, labOrdersTable, labResultsTable, appointmentsTable } from "@workspace/db";
import { eq, and } from "drizzle-orm";
import { requireAuth, requireRole } from "../lib/auth";

const router = Router();

// ── CSV export helper ─────────────────────────────────────────────────────────
function toCSV(headers: string[], rows: string[][]): string {
  const escape = (v: string) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  return [headers.map(escape).join(","), ...rows.map((r) => r.map(escape).join(","))].join("\n");
}

// ── PDF helpers (using pdfkit) ────────────────────────────────────────────────
async function buildPDF(sections: { title?: string; lines: string[] }[], title: string): Promise<Buffer> {
  const PDFDocument = (await import("pdfkit")).default;
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill("#0f766e");
    doc.fillColor("white").fontSize(22).font("Helvetica-Bold")
      .text("AetherCare HMS", 50, 25);
    doc.fontSize(10).font("Helvetica").text(title, 50, 52);

    doc.fillColor("#1e293b").moveDown(2);

    for (const section of sections) {
      if (section.title) {
        doc.fontSize(13).font("Helvetica-Bold").fillColor("#0f766e")
          .text(section.title, { underline: false });
        doc.moveDown(0.3);
        doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e2e8f0").stroke();
        doc.moveDown(0.5);
      }
      for (const line of section.lines) {
        doc.fontSize(10).font("Helvetica").fillColor("#334155").text(line, { lineGap: 4 });
      }
      doc.moveDown(1);
    }

    // Footer
    const bottomY = doc.page.height - 50;
    doc.moveTo(50, bottomY).lineTo(doc.page.width - 50, bottomY).strokeColor("#e2e8f0").stroke();
    doc.fontSize(8).fillColor("#94a3b8")
      .text(`Generated by AetherCare HMS  •  ${new Date().toLocaleString()}  •  For medical use only`, 50, bottomY + 8, { align: "center" });

    doc.end();
  });
}

// ── GET /export/prescription/:id/ ─────────────────────────────────────────────
router.get("/export/prescription/:id/", requireAuth, async (req, res) => {
  const { format = "pdf" } = req.query as Record<string, string>;
  const user = req.user!;
  const id = Number(req.params.id);

  const [rx] = await db.select({
    prescription: prescriptionsTable,
    patient: usersTable,
  })
    .from(prescriptionsTable)
    .leftJoin(usersTable, eq(prescriptionsTable.patientId, usersTable.id))
    .where(eq(prescriptionsTable.id, id));

  if (!rx) { res.status(404).json({ detail: "Prescription not found." }); return; }
  if (user.role === "patient" && rx.prescription.patientId !== user.id) {
    res.status(403).json({ detail: "Access denied." }); return;
  }

  const medicines = Array.isArray(rx.prescription.medicines) ? rx.prescription.medicines as any[] : [];
  const patientName = rx.patient ? `${rx.patient.firstName} ${rx.patient.lastName}`.trim() : "Unknown";
  const validUntil = rx.prescription.validUntil ? new Date(rx.prescription.validUntil).toLocaleDateString() : "N/A";
  const createdAt = rx.prescription.createdAt ? new Date(rx.prescription.createdAt).toLocaleDateString() : "N/A";

  if (format === "csv") {
    const headers = ["#", "Medicine", "Dosage", "Frequency", "Duration", "Instructions"];
    const rows = medicines.map((m: any, i: number) => [
      String(i + 1), m.name || "", m.dosage || "", m.frequency || "", m.duration || "", m.instructions || "",
    ]);
    const csv = toCSV(headers, rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", `attachment; filename=prescription-${id}.csv`);
    res.send(csv);
    return;
  }

  // PDF
  const sections = [
    { title: "Patient Information", lines: [`Patient: ${patientName}`, `Date Issued: ${createdAt}`, `Valid Until: ${validUntil}`, `Status: ${rx.prescription.status}`] },
    { title: "Prescribed Medicines", lines: medicines.map((m: any, i: number) => `${i + 1}. ${m.name || ""}${m.dosage ? ` — ${m.dosage}` : ""}${m.frequency ? `, ${m.frequency}` : ""}${m.duration ? ` for ${m.duration}` : ""}`) },
    ...(rx.prescription.instructions ? [{ title: "Instructions", lines: [rx.prescription.instructions] }] : []),
    { lines: ["⚠️ This prescription is valid only when issued by a licensed physician.", "Do not self-medicate. Consult your doctor for any queries."] },
  ];

  const pdf = await buildPDF(sections, `Prescription #${id}`);
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=prescription-${id}.pdf`);
  res.send(pdf);
});

// ── GET /export/billing/:id/ ─────────────────────────────────────────────────
router.get("/export/billing/:id/", requireAuth, async (req, res) => {
  const { format = "pdf" } = req.query as Record<string, string>;
  const user = req.user!;
  const id = Number(req.params.id);

  const [bill] = await db.select({
    billing: billingTable,
    patient: usersTable,
  })
    .from(billingTable)
    .leftJoin(usersTable, eq(billingTable.patientId, usersTable.id))
    .where(eq(billingTable.id, id));

  if (!bill) { res.status(404).json({ detail: "Invoice not found." }); return; }
  if (user.role === "patient" && bill.billing.patientId !== user.id) {
    res.status(403).json({ detail: "Access denied." }); return;
  }

  const patientName = bill.patient ? `${bill.patient.firstName} ${bill.patient.lastName}`.trim() : "Unknown";
  const amount = Number(bill.billing.amount || 0).toFixed(2);
  const invoiceDate = bill.billing.invoiceDate ? new Date(bill.billing.invoiceDate).toLocaleDateString() : "N/A";
  const dueDate = bill.billing.dueDate ? new Date(bill.billing.dueDate).toLocaleDateString() : "N/A";

  if (format === "csv") {
    const headers = ["Invoice ID", "Patient", "Amount (NPR)", "Status", "Invoice Date", "Due Date", "Description"];
    const rows = [[String(id), patientName, amount, bill.billing.status, invoiceDate, dueDate, bill.billing.description || ""]];
    const csv = toCSV(headers, rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", `attachment; filename=invoice-${id}.csv`);
    res.send(csv);
    return;
  }

  const sections = [
    { title: "Invoice Details", lines: [`Invoice ID: #${id}`, `Status: ${bill.billing.status?.toUpperCase()}`, `Invoice Date: ${invoiceDate}`, `Due Date: ${dueDate}`] },
    { title: "Patient", lines: [`Name: ${patientName}`] },
    { title: "Billing", lines: [`Description: ${bill.billing.description || "Hospital Services"}`, `Amount: NPR ${amount}`, `Insurance Provider: ${bill.billing.insuranceProvider || "N/A"}`, `Claim Number: ${bill.billing.claimNumber || "N/A"}`] },
    { lines: ["Payment is due on the specified due date. Contact billing for queries."] },
  ];

  const pdf = await buildPDF(sections, `Invoice #${id}`);
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=invoice-${id}.pdf`);
  res.send(pdf);
});

// ── GET /export/lab-order/:id/ ────────────────────────────────────────────────
router.get("/export/lab-order/:id/", requireAuth, async (req, res) => {
  const { format = "csv" } = req.query as Record<string, string>;
  const user = req.user!;
  const id = Number(req.params.id);

  const [row] = await db.select({ order: labOrdersTable, patient: usersTable })
    .from(labOrdersTable)
    .leftJoin(usersTable, eq(labOrdersTable.patientId, usersTable.id))
    .where(eq(labOrdersTable.id, id));

  if (!row) { res.status(404).json({ detail: "Lab order not found." }); return; }
  if (user.role === "patient" && row.order.patientId !== user.id) {
    res.status(403).json({ detail: "Access denied." }); return;
  }

  const results = await db.select().from(labResultsTable).where(eq(labResultsTable.labOrderId, id));
  const patientName = row.patient ? `${row.patient.firstName} ${row.patient.lastName}`.trim() : "Unknown";

  if (format === "csv") {
    const headers = ["Test Name", "Result Value", "Unit", "Reference Range", "Flag", "Status"];
    const rows = results.map((r) => [r.testName, r.resultValue || "", r.unit || "", r.referenceRange || "", r.abnormalFlag || "N", r.status]);
    const csv = toCSV(headers, rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", `attachment; filename=lab-report-${id}.csv`);
    res.send(csv);
    return;
  }

  const sections = [
    { title: "Lab Order", lines: [`Order No: ${row.order.orderNumber}`, `Patient: ${patientName}`, `Status: ${row.order.status}`, `Priority: ${row.order.priority}`, `Date: ${row.order.createdAt ? new Date(row.order.createdAt).toLocaleDateString() : ""}`] },
    { title: "Results", lines: results.length ? results.map((r) => `${r.testName}: ${r.resultValue || "Pending"} ${r.unit || ""} [Ref: ${r.referenceRange || "N/A"}]${r.abnormalFlag && r.abnormalFlag !== "N" ? ` ⚠️ ${r.abnormalFlag}` : ""}`) : ["No results yet"] },
    { lines: ["This is an official lab report from AetherCare Hospital. Consult your physician for interpretation."] },
  ];

  const pdf = await buildPDF(sections, `Lab Report — ${row.order.orderNumber}`);
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=lab-report-${id}.pdf`);
  res.send(pdf);
});

// ── GET /export/patients/ — bulk CSV ─────────────────────────────────────────
router.get("/export/patients/", requireAuth, requireRole("admin", "doctor", "reception"), async (req, res) => {
  const patients = await db.select({ user: usersTable }).from(usersTable).where(eq(usersTable.role, "patient"));
  const headers = ["ID", "First Name", "Last Name", "Email", "Phone", "Created"];
  const rows = patients.map((p) => [
    String(p.user.id), p.user.firstName, p.user.lastName, p.user.email,
    p.user.phone || "", p.user.createdAt ? new Date(p.user.createdAt).toLocaleDateString() : "",
  ]);
  const csv = toCSV(headers, rows);
  res.setHeader("Content-Type", "text/csv");
  res.setHeader("Content-Disposition", "attachment; filename=patients.csv");
  res.send(csv);
});

export default router;
