# Generated by Django 5.2.13 on 2026-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_billingpayment_gateway_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('nurse', 'Nurse'), ('reception', 'Reception'), ('pharmacist', 'Pharmacist'), ('lab', 'Lab Technician')], default='reception', max_length=20),
        ),
    ]
